contacts:
  email:
    label: "E-mail"
    value: "dhianapereira1@gmail.com"
    url: "mailto:dhianapereira1@gmail.com"
  linkedin:
    label: "LinkedIn"
    value: "linkedin.com/in/dhianapereira"
    url: "https://www.linkedin.com/in/dhianapereira/"
  github:
    label: "GitHub"
    value: "github.com/dhianapereira"
    url: "https://github.com/dhianapereira"
